/**
 * MOVO icon names -> Iconsax icon names (free set, https://iconsax.io).
 * Screens use the MOVO name on the left. Change the mapping here, then run `pnpm icons`.
 */
export const iconMap = {
  // navigation
  home: 'home-2',
  society: 'category',
  money: 'wallet-2',
  market: 'shop',
  me: 'profile-circle',
  back: 'arrow-left-01',
  chevronRight: 'arrow-right-02',
  chevronLeft: 'arrow-left-02',
  chevronUp: 'arrow-up-02',
  chevronDown: 'arrow-down-02',
  arrowRight: 'arrow-right-01',
  close: 'close-circle',
  more: 'more',
  menu: 'menu',
  // header and actions
  bell: 'notification',
  search: 'search-normal',
  filter: 'setting-4',
  settings: 'setting-2',
  add: 'add',
  addCircle: 'add-circle',
  edit: 'edit-2',
  trash: 'trash',
  share: 'share',
  copy: 'copy',
  eye: 'eye',
  heart: 'heart',
  star: 'star',
  like: 'like',
  verified: 'verify',
  check: 'tick-circle',
  checkSquare: 'tick-square',
  info: 'info-circle',
  warning: 'warning-2',
  sort: 'sort',
  export: 'export-arrow-01',
  refresh: 'refresh-circle',
  logout: 'logout-01',
  // society and people
  building: 'buildings-2',
  flat: 'house-2',
  location: 'location',
  map: 'map',
  people: 'profile-2user',
  group: 'people',
  user: 'user',
  userAdd: 'user-add',
  call: 'call',
  chat: 'message-text',
  mail: 'sms',
  send: 'send-2',
  language: 'language-square',
  globe: 'global',
  // modules
  notices: 'volume-high',
  meetings: 'calendar',
  events: 'ticket',
  directory: 'profile-2user',
  services: 'briefcase',
  parking: 'car',
  tasks: 'task-square',
  taskDone: 'clipboard-tick',
  duties: 'refresh-circle',
  rewards: 'medal-star',
  documents: 'document-text',
  audit: 'clipboard-text',
  emergency: 'danger',
  shield: 'shield-tick',
  help: 'message-question',
  support: 'headphone',
  // money
  wallet: 'wallet-2',
  receipt: 'receipt-2',
  card: 'card',
  bank: 'bank',
  upi: 'scan',
  moneyIn: 'money-recive',
  moneyOut: 'money-send',
  tag: 'tag',
  gift: 'gift',
  crown: 'crown',
  ranking: 'ranking',
  award: 'award',
  // time
  calendar: 'calendar',
  calendarTick: 'calendar-tick',
  clock: 'clock',
  timer: 'timer',
  // services categories and automation
  water: 'drop',
  electricity: 'flash',
  lift: 'building-3',
  cctv: 'camera',
  cleaning: 'broom',
  internet: 'wifi',
  gate: 'lock',
  key: 'key',
  lamp: 'lamp-charge',
  automation: 'cpu-setting',
  camera: 'camera',
  gallery: 'gallery',
  image: 'image',
  box: 'box',
  truck: 'truck',
  sun: 'sun',
  moon: 'moon',
  bag: 'bag-2',
  cup: 'cup',
  security: 'security-safe',
  // services categories (M4)
  ac: 'ai-ac',
  paint: 'paintbucket',
  carpentry: 'ruler',
  tools: 'ai-tools',
  pest: 'bucket',
  laundry: 'wind',
  gas: 'gas-station',
  mobile: 'mobile',
  monitor: 'monitor',
  health: 'health',
  // emergency (M4)
  hospital: 'hospital',
  fire: 'fire',
  alarm: 'alarm',
  callCalling: 'call-calling',
  evCharge: 'battery-charging',
} as const;

export type IconName = keyof typeof iconMap;
