/** Every key includes the society id so switching societies never shows stale data. */
export const keys = {
  me: {
    context: ['me', 'context'] as const,
    notifications: ['me', 'notifications'] as const,
  },
  society: (id: string) => ({
    all: ['society', id] as const,
    profile: ['society', id, 'profile'] as const,
    home: ['society', id, 'home'] as const,
    notices: (status: string) => ['society', id, 'notices', status] as const,
    notice: (noticeId: string) => ['society', id, 'notice', noticeId] as const,
    members: (q: string) => ['society', id, 'members', q] as const,
    member: (membershipId: string) => ['society', id, 'member', membershipId] as const,
    roles: ['society', id, 'roles'] as const,
    modules: ['society', id, 'modules'] as const,
    audit: (area: string) => ['society', id, 'audit', area] as const,
    buildings: ['society', id, 'buildings'] as const,
    flats: ['society', id, 'flats'] as const,
    invitations: ['society', id, 'invitations'] as const,
    joinRequests: ['society', id, 'join-requests'] as const,
    parking: ['society', id, 'parking'] as const,
    parkingMine: ['society', id, 'parking', 'me'] as const,
    parkingSlots: (filter: string) => ['society', id, 'parking', 'slots', filter] as const,
    vehicles: (q: string) => ['society', id, 'parking', 'vehicles', q] as const,
    vendorCategories: ['society', id, 'vendors', 'categories'] as const,
    vendors: (filter: string) => ['society', id, 'vendors', 'list', filter] as const,
    vendor: (vendorId: string) => ['society', id, 'vendors', 'one', vendorId] as const,
    emergencyContacts: ['society', id, 'emergency', 'contacts'] as const,
    alerts: (status: string) => ['society', id, 'emergency', 'alerts', status] as const,
    alert: (alertId: string) => ['society', id, 'emergency', 'alert', alertId] as const,
    meetings: (when: string) => ['society', id, 'meetings', 'list', when] as const,
    meeting: (meetingId: string) => ['society', id, 'meetings', 'one', meetingId] as const,
    events: (when: string) => ['society', id, 'events', 'list', when] as const,
    event: (eventId: string) => ['society', id, 'events', 'one', eventId] as const,
    eventRsvps: (eventId: string) => ['society', id, 'events', 'rsvps', eventId] as const,
    money: ['society', id, 'money'] as const,
    myDues: ['society', id, 'money', 'me'] as const,
    flatAccount: (flatId: string) => ['society', id, 'money', 'flat', flatId] as const,
    bill: (billId: string) => ['society', id, 'money', 'bill', billId] as const,
    payments: (flatId: string) => ['society', id, 'money', 'payments', flatId] as const,
    payment: (paymentId: string) => ['society', id, 'money', 'payment', paymentId] as const,
    collection: ['society', id, 'money', 'collection'] as const,
    plans: ['society', id, 'money', 'plans'] as const,
    instructions: ['society', id, 'money', 'instructions'] as const,
    finance: ['society', id, 'finance'] as const,
    expenses: (filter: string) => ['society', id, 'finance', 'expenses', filter] as const,
    expense: (expenseId: string) => ['society', id, 'finance', 'expense', expenseId] as const,
    expenseCategories: ['society', id, 'finance', 'categories'] as const,
    report: (fy: string) => ['society', id, 'finance', 'report', fy] as const,
    income: (fy: string) => ['society', id, 'finance', 'income', fy] as const,
    duties: ['society', id, 'duties'] as const,
    dutyList: (mine: boolean) => ['society', id, 'duties', 'list', mine] as const,
    duty: (dutyId: string) => ['society', id, 'duties', 'one', dutyId] as const,
    tasks: ['society', id, 'tasks'] as const,
    taskList: (view: string) => ['society', id, 'tasks', 'list', view] as const,
    task: (taskId: string) => ['society', id, 'tasks', 'one', taskId] as const,
    rewards: ['society', id, 'rewards'] as const,
    rewardsMine: ['society', id, 'rewards', 'me'] as const,
    leaderboard: ['society', id, 'rewards', 'board'] as const,
    market: ['society', id, 'market'] as const,
    listings: (filter: string) => ['society', id, 'market', 'listings', filter] as const,
    listing: (listingId: string) => ['society', id, 'market', 'listing', listingId] as const,
    myListings: ['society', id, 'market', 'mine'] as const,
    orders: (role: string) => ['society', id, 'market', 'orders', role] as const,
    order: (orderId: string) => ['society', id, 'market', 'order', orderId] as const,
    marketReports: ['society', id, 'market', 'reports'] as const,
  }),
  join: { preview: (code: string) => ['join', 'preview', code] as const },
};
