/**
 * Reads the icons named in src/icons/icon-map.ts from the `iconsax` package (free set)
 * and writes src/icons/generated/icon-data.ts with their SVG nodes in `linear` and `bold` styles.
 * Colors are normalised to currentColor so one component can tint any icon.
 */
import { mkdirSync, readFileSync, writeFileSync } from 'node:fs';
import { createRequire } from 'node:module';
import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';
import { createJiti } from 'jiti';

const here = dirname(fileURLToPath(import.meta.url));
const root = resolve(here, '..');
const require = createRequire(import.meta.url);
const manifestPath = require.resolve('iconsax/manifest.json');
const dataDir = resolve(dirname(manifestPath), 'data');
const manifest = JSON.parse(readFileSync(manifestPath, 'utf8'));
const jiti = createJiti(import.meta.url);
const { iconMap } = await jiti.import(resolve(root, 'src/icons/icon-map.ts'));

const STYLES = ['linear', 'bold'];
const COLOR_RE = /^(#292d32|#fff(fff)?|white|#000(000)?|black|currentcolor)$/i;
const ELEMENT_RE = /<(path|circle|rect|line|polyline|polygon|ellipse)\b([^>]*?)\/?>/g;
const ATTR_RE = /([a-zA-Z_:][-a-zA-Z0-9_:.]*)\s*=\s*"([^"]*)"/g;
const KEEP = new Set([
  'd',
  'cx',
  'cy',
  'r',
  'rx',
  'ry',
  'x',
  'y',
  'x1',
  'y1',
  'x2',
  'y2',
  'width',
  'height',
  'points',
  'fill',
  'stroke',
  'stroke-width',
  'stroke-linecap',
  'stroke-linejoin',
  'stroke-miterlimit',
  'fill-rule',
  'clip-rule',
  'opacity',
  'fill-opacity',
  'stroke-opacity',
  'transform',
]);

const categoryCache = new Map();
const loadCategory = (category) => {
  if (!categoryCache.has(category)) {
    categoryCache.set(
      category,
      JSON.parse(readFileSync(resolve(dataDir, `${category}.json`), 'utf8')),
    );
  }
  return categoryCache.get(category);
};

const parseSvg = (svg) => {
  const rootFill = /<svg\b[^>]*\bfill="([^"]*)"/.exec(svg)?.[1] ?? 'none';
  const body = svg.replace(/<defs>[\s\S]*?<\/defs>/g, '').replace(/<mask[\s\S]*?<\/mask>/g, '');
  const nodes = [];
  for (const m of body.matchAll(ELEMENT_RE)) {
    const tag = m[1];
    const attrs = {};
    for (const a of m[2].matchAll(ATTR_RE)) {
      const [, k, v] = a;
      if (!KEEP.has(k)) continue;
      attrs[k] = (k === 'fill' || k === 'stroke') && COLOR_RE.test(v) ? 'currentColor' : v;
    }
    if (tag === 'rect' && attrs.width === '24' && attrs.height === '24' && !attrs.rx) continue; // clip helper
    if (!('fill' in attrs)) attrs.fill = rootFill === 'none' ? 'none' : 'currentColor';
    nodes.push({ tag, attrs });
  }
  return nodes;
};

const out = {};
const missing = [];
for (const [movoName, iconsaxName] of Object.entries(iconMap)) {
  const entry = manifest[iconsaxName];
  if (!entry) {
    missing.push(`${movoName} -> ${iconsaxName}`);
    continue;
  }
  const svgs = loadCategory(entry.category)[iconsaxName];
  out[movoName] = {};
  for (const style of STYLES) {
    const svg = svgs?.[style];
    if (!svg) {
      missing.push(`${movoName} -> ${iconsaxName} (${style})`);
      continue;
    }
    out[movoName][style] = parseSvg(svg);
  }
}
if (missing.length) {
  console.error(`Missing icons:\n  ${missing.join('\n  ')}`);
  process.exit(1);
}

const header = `/* Generated by scripts/build-icons.mjs from the Iconsax free set. Do not edit. Run \`pnpm --filter @movo/design-system icons\`. */
import type { IconName } from '../icon-map';
import type { IconNode, IconStyle } from '../types';

export const iconData: Record<IconName, Record<IconStyle, readonly IconNode[]>> = `;
mkdirSync(resolve(root, 'src/icons/generated'), { recursive: true });
const file = resolve(root, 'src/icons/generated/icon-data.ts');
writeFileSync(file, `${header}${JSON.stringify(out, null, 2)};\n`);
console.log(`wrote ${file}: ${Object.keys(out).length} icons x ${STYLES.length} styles`);
